# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciclistasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiclistaEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='ciclista',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='ciclistaequipo',
            name='ciclista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclistasapp.Ciclista'),
        ),
        migrations.AddField(
            model_name='ciclistaequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclistasapp.Equipo'),
        ),
    ]
