# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclistasapp', '0002_auto_20190425_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
