# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciclistasapp', '0003_equipo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prueba', models.CharField(max_length=50, unique=True)),
                ('anio_edicion', models.CharField(max_length=50)),
                ('etapas', models.IntegerField()),
                ('total_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ciclista_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclistasapp.Ciclista')),
            ],
        ),
        migrations.CreateModel(
            name='PruebasEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pruebasequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclistasapp.Equipo'),
        ),
        migrations.AddField(
            model_name='pruebasequipo',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclistasapp.Prueba'),
        ),
        migrations.AlterUniqueTogether(
            name='pruebasequipo',
            unique_together=set([('equipo', 'prueba')]),
        ),
    ]
