# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclistasapp', '0004_auto_20190425_1009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pruebasequipo',
            unique_together=set([]),
        ),
    ]
